a = {
  result:
    '{"CORE": [["CS2030", "Data Structures and Algorithms", "B", 0], ["CS2130", "Data Structures and Algorithms Lab", "PA4", 0], ["CS3060", "Computer Architecture", "G", 0], ["CS3160", "Computer Architecture Lab", "PA2", 0], ["DS2020", "Introduction to Artificial Intelligence", "C+", "PA3"]], "SME": [["MA2041", "Probability and Statistics", "F", 0], ["MA2032", "Numerical Analysis", "F", 0], ["PH4602", "Introduction to Special Relativity", "G", 0], ["PH3601", "Quantum Mechanics for Engineers", "G", 0], ["CY3601", "Electrochemistry and Corrosions", "G", 0], ["CY4001", "Industrial Chemistry", "F", 0]], "HSE": [["HS2031", "Principles of Economics (40)", "H", 0], ["HS2302", "Introduction to Language and Society(40)", "H", 0], ["HSxxxx", "Mental Health and Law (tentative title , course yet to be approved) (40)", "H", 0], ["HS2304", "Culture and Gender Performativity(40)  ", "H", 0]], "GCE": [["PH3601", "Quantum Mechanics for Engineers", "G", 0], ["PH4602", "Introduction to Special Relativity", "G", 0], ["HS4605", "Foundation of Linguistics (40)", "G", 0], ["HS5009", "Mental Health and Society in the Global South (40)", "G", 0], ["HS", "Contemporary Issues in Economic Development (30)", "G", 0], ["HS4607M", "German I (NPTEL)", "NA", 0], ["HS3605", "Introduction to Modern Indian Political Thought (NPTEL)", "NA", 0], ["ME3522", "Introduction to Finite Element Methods", "G", 0], ["CY3601", "Electrochemistry and Corrosions", "G", 0], ["ES 5601", "Sustainability Analysis and Design", "G", 0], ["BS5001", "Fundamentals of Nanobiotechnology", "G", 0], ["ES5XXXX", "Photosynthesis", "G", 0], ["EE5XXXX", "Computer Graphics (40)", "G", 0], ["ME5632", "Computational Methods for Inverse Problems", "G", 0], ["GN1005", "GN1005: How to prepare for internship and job search?", "E4", 0], ["CY4001", "Industrial Chemistry", "F", 0], ["HS3627", "Engineering Economics (40)*", "F", 0]]}',
};



// make options unselectable if timings clash
// auto select core courses
